spring:
  data:
    mongodb:
      username: nazirka
      password: nazirka
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
