spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: nazirka
    password: nazirka
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.flyway.password}
    password: ${spring.datasource.password}
server:
  port: 8050
